/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package program;

/**
 *
 * @author OPERATOR SLEBEWWW
 */
public class templet extends javax.swing.JFrame {

    /**
     * Creates new form templet
     */
    public templet() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        kode_pesawat = new javax.swing.JComboBox<>();
        nama_pesawat = new javax.swing.JTextField();
        kelas_pesawat = new javax.swing.JComboBox<>();
        harga_tiket = new javax.swing.JTextField();
        jumlah_tiket = new javax.swing.JTextField();
        total_bayar = new javax.swing.JTextField();
        uang_bayar = new javax.swing.JTextField();
        hitung = new javax.swing.JButton();
        uang_kembali = new javax.swing.JTextField();
        input = new javax.swing.JButton();
        keluar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("PENJUALAN TIKET PESAWAT");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        jLabel2.setText("Kode Pesawat");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jLabel3.setText("Nama Pesawat");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jLabel4.setText("Kelas Pesawat");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jLabel5.setText("Harga Tiket");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jLabel6.setText("Jumlah Tiket");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jLabel7.setText("Total Bayar");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        jLabel8.setText("Uang Bayar");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        jLabel9.setText("Uang Kembali");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        kode_pesawat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "== PILIH ==", "MPT", "GRD", "BTV" }));
        kode_pesawat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kode_pesawatActionPerformed(evt);
            }
        });
        jPanel1.add(kode_pesawat, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 170, -1));
        jPanel1.add(nama_pesawat, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 170, -1));

        kelas_pesawat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "== PILIH ==", "Kelas 1", "Kelas 2", "Kelas 3" }));
        kelas_pesawat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kelas_pesawatActionPerformed(evt);
            }
        });
        jPanel1.add(kelas_pesawat, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 170, -1));
        jPanel1.add(harga_tiket, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 170, -1));

        jumlah_tiket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlah_tiketActionPerformed(evt);
            }
        });
        jumlah_tiket.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jumlah_tiketKeyPressed(evt);
            }
        });
        jPanel1.add(jumlah_tiket, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 170, -1));
        jPanel1.add(total_bayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 170, -1));
        jPanel1.add(uang_bayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 170, -1));

        hitung.setText("HITUNG");
        hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungActionPerformed(evt);
            }
        });
        jPanel1.add(hitung, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, -1, -1));
        jPanel1.add(uang_kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 170, -1));

        input.setText("INPUT");
        input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputActionPerformed(evt);
            }
        });
        jPanel1.add(input, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, -1, -1));

        keluar.setText("KELUAR");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        jPanel1.add(keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, -1, -1));

        jLabel10.setText("Rp.");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 20, 20));

        jLabel11.setText("Rp.");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 20, 20));

        jLabel12.setText("Rp.");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 20, 20));

        jLabel13.setText("Rp.");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 20, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kode_pesawatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kode_pesawatActionPerformed
        // TODO add your handling code here:
        if (kode_pesawat.getSelectedItem().equals("MPT")) {
            nama_pesawat.setText("Merpati");
        } else if (kode_pesawat.getSelectedItem().equals("GRD")) {
            nama_pesawat.setText("Garuda");
        } else if (kode_pesawat.getSelectedItem().equals("BTV")) {
            nama_pesawat.setText("Batavia");
        }
    }//GEN-LAST:event_kode_pesawatActionPerformed

    private void kelas_pesawatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kelas_pesawatActionPerformed
        // TODO add your handling code here:
        if (kode_pesawat.getSelectedItem().equals("MPT")) {
            if (kelas_pesawat.getSelectedItem().equals("Kelas 1")) {
                harga_tiket.setText("1500000");
            } else if (kelas_pesawat.getSelectedItem().equals("Kelas 2")) {
                harga_tiket.setText("900000");
            } else if (kelas_pesawat.getSelectedItem().equals("Kelas 3")) {
                harga_tiket.setText("500000");
            }
        } else if (kode_pesawat.getSelectedItem().equals("GRD")) {
            if (kelas_pesawat.getSelectedItem().equals("Kelas 1")) {
                harga_tiket.setText("1200000");
            } else if (kelas_pesawat.getSelectedItem().equals("Kelas 2")) {
                harga_tiket.setText("800000");
            } else if (kelas_pesawat.getSelectedItem().equals("Kelas 3")) {
                harga_tiket.setText("400000");
            }
        } else if (kode_pesawat.getSelectedItem().equals("BTV")) {
            if (kelas_pesawat.getSelectedItem().equals("Kelas 1")) {
                harga_tiket.setText("1000000");
            } else if (kelas_pesawat.getSelectedItem().equals("Kelas 2")) {
                harga_tiket.setText("700000");
            } else if (kelas_pesawat.getSelectedItem().equals("Kelas 3")) {
                harga_tiket.setText("300000");
            }
        }
    }//GEN-LAST:event_kelas_pesawatActionPerformed

    private void jumlah_tiketKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jumlah_tiketKeyPressed
        // TODO add your handling code here:
        int harga=Integer.parseInt(harga_tiket.getText());  
        int jumlah=Integer.parseInt(jumlah_tiket.getText());  
        int hasil=harga*jumlah;  
        total_bayar.setText(Integer.toString(hasil));  
    }//GEN-LAST:event_jumlah_tiketKeyPressed

    private void hitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungActionPerformed
        // TODO add your handling code here:
        int total = Integer.parseInt(total_bayar.getText());
        int uang = Integer.parseInt(uang_bayar.getText());
        int hasil = uang-total;
        uang_kembali.setText(Integer.toString(hasil));
    }//GEN-LAST:event_hitungActionPerformed

    private void inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputActionPerformed
        // TODO add your handling code here:
        nama_pesawat.setText("");
        harga_tiket.setText("");
        jumlah_tiket.setText("");
        total_bayar.setText("");
        uang_bayar.setText("");
        uang_kembali.setText("");
        kelas_pesawat.setSelectedIndex(0);
        kode_pesawat.setSelectedIndex(0);
    }//GEN-LAST:event_inputActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_keluarActionPerformed

    private void jumlah_tiketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlah_tiketActionPerformed

    }//GEN-LAST:event_jumlah_tiketActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(templet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(templet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(templet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(templet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new templet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField harga_tiket;
    private javax.swing.JButton hitung;
    private javax.swing.JButton input;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jumlah_tiket;
    private javax.swing.JComboBox<String> kelas_pesawat;
    private javax.swing.JButton keluar;
    private javax.swing.JComboBox<String> kode_pesawat;
    private javax.swing.JTextField nama_pesawat;
    private javax.swing.JTextField total_bayar;
    private javax.swing.JTextField uang_bayar;
    private javax.swing.JTextField uang_kembali;
    // End of variables declaration//GEN-END:variables
}
